---
- name: Update Apt Repos
  apt:
    update_cache: yes
    upgrade: 'yes'
    
    cache_valid_time: 86400 
- name: Install Java
  apt:
    name: default-jdk
    state: latest
    update_cache: yes

- name: Add new group tomcat
  group:
    name: tomcat

- name: Add new user tomcat
  user:
    name: tomcat
    group: tomcat
    home: /opt/tomcat
    create_home: no

- name: Make new directory
  file:
    path: /opt/tomcat
    state: directory
    mode: '0755'

- name: Download tomcat server packages
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
    dest: /opt/tomcat

- name: Extract tomcat packages
  unarchive:
    src: /opt/tomcat/apache-tomcat-9.0.65.tar.gz
    dest: /opt/tomcat

- name: Change ownership
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory

- name: Copy Tomcat service from local to remote
  copy:
    src: tomcat.service
    dest: /etc/systemd/system/
    mode: 0755

- name: Start and enable Tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: true
    daemon_reload: true
